// Date: 02-08-2013 22:59:46
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package nekpek.mod.Naturalis.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class NaturalisFish extends ModelBase
    {
        // fields
        ModelRenderer headtop;
        ModelRenderer suckermouth;
        ModelRenderer mouth;
        ModelRenderer bodysection1;
        ModelRenderer bodysection2;
        ModelRenderer bodysection3;
        ModelRenderer bodysection4;
        ModelRenderer bodysection5;
        ModelRenderer bodysection6;
        ModelRenderer Tail;
        ModelRenderer Tail2;
        ModelRenderer Tail3;
        ModelRenderer bellyFin;
        ModelRenderer BackFin;
        ModelRenderer SideFin;
        ModelRenderer SideFin2;

        public NaturalisFish()
            {
                textureWidth = 128;
                textureHeight = 64;

                headtop = new ModelRenderer(this, 82, 49);
                headtop.addBox(-3F, 0F, 0F, 6, 8, 7);
                headtop.setRotationPoint(0F, 20F, -14F);
                headtop.setTextureSize(128, 64);
                headtop.mirror = true;
                setRotation(headtop, 0.7853982F, 0F, 0F);
                suckermouth = new ModelRenderer(this, 108, 54);
                suckermouth.addBox(-2.5F, 0F, 0F, 5, 5, 5);
                suckermouth.setRotationPoint(0F, 20F, -14F);
                suckermouth.setTextureSize(128, 64);
                suckermouth.mirror = true;
                setRotation(suckermouth, 0F, 0F, 0F);
                mouth = new ModelRenderer(this, 110, 45);
                mouth.addBox(-2.5F, -4F, -2F, 5, 6, 3);
                mouth.setRotationPoint(0F, 23F, -9F);
                mouth.setTextureSize(128, 64);
                mouth.mirror = true;
                setRotation(mouth, 0.7853982F, 0F, 0F);
                bodysection1 = new ModelRenderer(this, 0, 0);
                bodysection1.addBox(-4F, -5F, 0F, 8, 10, 5);
                bodysection1.setRotationPoint(0F, 20F, -9F);
                bodysection1.setTextureSize(128, 64);
                bodysection1.mirror = true;
                setRotation(bodysection1, 0F, 0F, 0F);
                bodysection2 = new ModelRenderer(this, 26, 0);
                bodysection2.addBox(-4.466667F, -5.466667F, 0F, 9, 11, 8);
                bodysection2.setRotationPoint(0F, 20F, -5F);
                bodysection2.setTextureSize(128, 64);
                bodysection2.mirror = true;
                setRotation(bodysection2, 0F, 0F, 0F);
                bodysection3 = new ModelRenderer(this, 60, 0);
                bodysection3.addBox(-4F, -4F, 0F, 8, 9, 8);
                bodysection3.setRotationPoint(0F, 20F, 2F);
                bodysection3.setTextureSize(128, 64);
                bodysection3.mirror = true;
                setRotation(bodysection3, 0F, 0F, 0F);
                bodysection4 = new ModelRenderer(this, 92, 0);
                bodysection4.addBox(-3.5F, -3F, 0F, 7, 7, 5);
                bodysection4.setRotationPoint(0F, 20F, 9F);
                bodysection4.setTextureSize(128, 64);
                bodysection4.mirror = true;
                setRotation(bodysection4, 0F, 0F, 0F);
                bodysection5 = new ModelRenderer(this, 0, 21);
                bodysection5.addBox(-2.5F, -2F, 0F, 5, 5, 5);
                bodysection5.setRotationPoint(0F, 19F, 13F);
                bodysection5.setTextureSize(128, 64);
                bodysection5.mirror = true;
                setRotation(bodysection5, 0F, 0F, 0F);
                bodysection6 = new ModelRenderer(this, 20, 21);
                bodysection6.addBox(-1F, -1F, 0F, 2, 3, 4);
                bodysection6.setRotationPoint(0F, 19F, 17F);
                bodysection6.setTextureSize(128, 64);
                bodysection6.mirror = true;
                setRotation(bodysection6, 0F, 0F, 0F);
                Tail = new ModelRenderer(this, 0, 44);
                Tail.addBox(0F, -2F, -2F, 0, 10, 10);
                Tail.setRotationPoint(0F, 19F, 20F);
                Tail.setTextureSize(128, 64);
                Tail.mirror = true;
                setRotation(Tail, 0.7853982F, 0F, 0F);
                Tail2 = new ModelRenderer(this, 20, 50);
                Tail2.addBox(-1F, 3F, 2F, 0, 6, 8);
                Tail2.setRotationPoint(0F, 19F, 13F);
                Tail2.setTextureSize(128, 64);
                Tail2.mirror = true;
                setRotation(Tail2, 0F, 0F, 0.2617994F);
                Tail3 = new ModelRenderer(this, 20, 50);
                Tail3.addBox(1F, 3F, 2F, 0, 6, 8);
                Tail3.setRotationPoint(0F, 19F, 13F);
                Tail3.setTextureSize(128, 64);
                Tail3.mirror = true;
                setRotation(Tail3, 0F, 0F, -0.2617994F);
                bellyFin = new ModelRenderer(this, 36, 32);
                bellyFin.addBox(0F, -1F, -6F, 0, 12, 20);
                bellyFin.setRotationPoint(0F, 24F, 0F);
                bellyFin.setTextureSize(128, 64);
                bellyFin.mirror = true;
                setRotation(bellyFin, 0.2443461F, 0F, 0F);
                BackFin = new ModelRenderer(this, 36, 32);
                BackFin.addBox(0F, -10F, -6F, 0, 12, 20);
                BackFin.setRotationPoint(0F, 15F, 1F);
                BackFin.setTextureSize(128, 64);
                BackFin.mirror = true;
                setRotation(BackFin, -0.2268928F, 0F, 0F);
                SideFin = new ModelRenderer(this, 0, 27);
                SideFin.addBox(0F, -6F, 0F, 0, 12, 15);
                SideFin.setRotationPoint(-4F, 20F, -4F);
                SideFin.setTextureSize(128, 64);
                SideFin.mirror = true;
                setRotation(SideFin, 0F, -0.3490659F, 0F);
                SideFin2 = new ModelRenderer(this, 0, 27);
                SideFin2.addBox(0F, -6F, 0F, 0, 12, 15);
                SideFin2.setRotationPoint(4F, 20F, -4F);
                SideFin2.setTextureSize(128, 64);
                SideFin2.mirror = true;
                setRotation(SideFin2, 0F, 0.3490659F, 0F);
            }

        @Override
        public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
            {
                // super.render(entity, f, f1, f2, f3, f4, f5);
                setRotationAngles(f, f1, f2, f3, f4, f5, entity);
                headtop.render(f5);
                suckermouth.render(f5);
                mouth.render(f5);
                bodysection1.render(f5);
                bodysection2.render(f5);
                bodysection3.render(f5);
                bodysection4.render(f5);
                bodysection5.render(f5);
                bodysection6.render(f5);
                Tail.render(f5);
                Tail2.render(f5);
                Tail3.render(f5);
                bellyFin.render(f5);
                BackFin.render(f5);
                SideFin.render(f5);
                SideFin2.render(f5);
            }

        private void setRotation(ModelRenderer model, float x, float y, float z)
            {
                model.rotateAngleX = x;
                model.rotateAngleY = y;
                model.rotateAngleZ = z;
            }

        @Override
        public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
            {
                // super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
            }
    }
